name: Kyvos Import CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  KYVOS_HOME: /home/impadmin/CICD_Utility_2023.5R3
  KYVOS_ENTITIES_PATH: /home/impadmin/CICD_Utility_2023.5R3/GitRepo/automation/KyvosEntities

jobs:
  import-job:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x $KYVOS_HOME/ImportKyvosEntities.sh

      - name: Run Kyvos Import Script
        run: |
          cd $KYVOS_HOME
          ./ImportKyvosEntities.sh "$KYVOS_ENTITIES_PATH"

